oc_platform_home:
    path:      /platform/{page}
    defaults: 
        _controller: OCPlatformBundle:Advert:index
        page:    1
    requirements:
        page:    \d*

oc_platform_view:
    path:      platform/advert/{id}
    defaults:  
        _controller: OCPlatformBundle:Advert:view
    requirements:
        id:    \d


oc_platform_add:
    path:      platform/add
    defaults: { _controller: OCPlatformBundle:Advert:add }
