<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertSkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListAdvertSkills($advertId)
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->innerJoin('a.skill', 's')
            ->where('a.advert = :advertId')
            ->setParameter(':advertId', $advertId)
            ->addSelect('s');

        return $query = $qb
            ->getQuery()
            ->getResult();
    }
}
