<?php

namespace OC\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    // public function getAdvertWithCategories(array $categoryNames)
    // {
    //     $qb = $this
    //     ->createQueryBuilder('a')
    //     ->innerJoin('a.categories', 'c')
    //     ->addSelect('c');

    //     $qb->where($qb->expr()->in('c.name', $categoryNames));

    //     $query = $qb->getQuery();

    //     return $query->getResult();
    // }

    // public function getLastAdverts($limit)
    // {
    //     $qb = $this 
    //         ->createQueryBuilder('a')
    //         ->setMaxResults($limit);
            
    //     $qb->orderBy('a.id', 'DESC');

    //     return $query = $qb
    //         ->getQUery()
    //         ->getResult();
    // }

    public function getAdverts()
    {
        $query = $this->createQueryBuilder('a')
            ->leftJoin('a.categories', 'c')
            ->addSelect('c')
            ->leftJoin('a.image', 'i')
            ->addSelect('i')
            ->orderBy('a.date', 'DESC')
            ->getQuery();

        return $query->getResult();
    }
}
