oc_core_homepage:
    path:     /{home}
    defaults: 
        _controller: OCCoreBundle:Home:index
        home: 'home'
    requirements:
        home: 'home'

oc_core_contact:
    path:     /contact
    defaults: 
        _controller: OCCoreBundle:Home:contact
